from dataclasses import dataclass


@dataclass
class Constants:

    PORT_NR = 8081
    DATA_BUFFER_SIZE = 64

    COMMAND_PING = "0"
    COMMAND_SHUTDOWN_NOW = "1"
    COMMAND_SCHEDULED_SHUTDOWN = "2"
    COMMAND_ABORT_SHUTDOWN = "3"
    COMMAND_RESTART = "4"
    COMMAND_SET_VOLUME = "5"
    COMMAND_GET_VOLUME = "6"
    COMMAND_MUTE = "7"
    COMMAND_UNMUTE = "8"
    COMMAND_MOUSE_MOVE = "9"
    COMMAND_MOUSE_LEFT = "10"
    COMMAND_MOUSE_RIGHT = "11"

    FEEDBACK_AWAITING_PARAMS = "ready"
    FEEDBACK_SUCCEED = "ok"
    FEEDBACK_FAILED = "failed"
    FEEDBACK_PONG = "pong"
    FEEDBACK_VOLUME_LEVEL = "volume"

    SEPARATOR = '&'
    ENCODING = 'utf-8'
